server:
  port: 8888
  servlet:
    context-path: /soa/
#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/boot-soa?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#Logging
logging:
  file:
    name: boot-soa.log

#Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-configuration.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.com.agree.soa.model
